### ISSUE TITLE
Cannot find name 'it'.

### ISSUE THREAD

**Issue by ghost** [arosh/karma-power-assert-typescript-mocha-webpack-sample#2]
現在のmasterブランチで以下を実行すると、

```
 $(npm bin)/karma start
```

以下のエラーが出ます。

```
ERROR in ./test/browser/sub_test.ts
(4,1): error TS2304: Cannot find name 'it'.
```

原因は分かりますでしょうか？

**Comment by ghost** [comment]
tsc でコンパイルはできます。

```
$(npm bin)/tsc -p .
```

mochaでテストもできるようです。

```
$ $(npm bin)/mocha --require intelli-espower-loader test/browser/sub_test.js


  1) 2 + 3 = 5

  0 passing (43s)
  1 failing
```

**Comment by ghost** [comment]
以下の設定が必要のようでした。

http://stackoverflow.com/questions/39816482/how-to-import-describe-and-it-from-mocha-in-typescript

**Comment by arosh** [comment]
@ogis-onishi 
コメントありがとうございます。
最近TypeScriptを使っていなかったので，動かなくなっていることに気づいていませんでした。
ブログのほうにも追記しておきます。
